---
- name: Hello
  hosts: all
  gather_facts: False
  execution_strategy: parallel
  sources:
    - ansible.eda.range:
        limit: 1
  rules:
    - name: JSON Post
      condition: true
      action:
        json_post:
          uri: http://localhost:8000/webhook
          data:
            message: hi
...
